export const PEEPS_PARTS = ['accessories', 'body', 'face', 'head', 'pose/sitting', 'pose/standing', 'facial-hair'];
export const TEST_PEEPS_PARTS = ['test'];
export const PEEPS_BUILD_PATH = 'build/peeps';
export const PEEPS_SRC_ASSETS_PATH = 'src/assets/peeps';
export const PEEPS_BUILD_ASSETS_PATH = 'build/peeps/assets';
export const PEEPS_LIB_ASSETS_PATH = 'lib/assets';
export const PEEPS_BUILD_COMPONENTS_PATH = 'build/peeps/components';
export const PEEPS_LIB_COMPONENTS_PATH = 'lib/components';
export const FOLDERS_TO_CLEAR = ['build', 'dist', 'lib'];